music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, only: [:create, :edit, :update, :show, :destroy] do
    resources :tracks, only: :new
  end

  resources :tracks, only: [:create, :edit, :update, :show, :destroy]

  root to: 'bands#index'
end

music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  year       :integer          not null
#  studio     :boolean          default(TRUE)
#  live       :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :band_id, :year, presence: true

  belongs_to :band

  has_many :tracks
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums

  has_many :tracks,
           through: :albums
end

music_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  ord        :integer          not null
#  lyrics     :text
#  track_type :string           default("regular")
#  album_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :title, :ord, :album_id, presence: true
  validates :track_type,
            presence: true,
            inclusion: {
              in: %w(regular bonus),
              message: "%{value} is not a valid type"
            }

  belongs_to :album

  has_one :band,
          through: :album
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: { message: 'Must have a password'}
  validates :password, length: { minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  def self.find_by_credentials(options={})
    user = User.find_by(email: options[:email])
    return user if user &&
        BCrypt::Password.new(user.password_digest).is_password?(options[:password])
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(@password)
  end

  def reset_session_token! # only works with saved user instances
    self.update(session_token: SecureRandom.urlsafe_base64)
  end

  def ensure_session_token # works with unsaved user instances
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :ensure_logged_in

  def show
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @band = Band.find(@album.band_id)
    if @album.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
  end

  def update
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    if @album.update(album_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    Album.find(params[:id]).delete
    redirect_to request.referrer
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :year, :studio, :live)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    @current_user = user
  end

  def logout!
    current_user.reset_session_token!
    session_token[:session_token] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def ensure_logged_in
    if current_user.nil?
      redirect_to new_session_url
    end
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in
  
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(name: params[:band][:name])
    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(name: params[:band][:name])
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.delete
    redirect_to bands_url
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_logged_in, except: [:new, :create]

  def new
  end

  def create
    login!(User.find_by_credentials(user_params))
    redirect_to user_url(current_user)
  end

  def destroy
    current_user && current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
    redirect_to new_session_url
  end
end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, except: [:new, :create]

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to '/'
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\"
            name=\"authenticity_token\"
            value=\"#{form_authenticity_token}\">".html_safe
  end
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/_album.html.erb
Title: <%= album.title %>
<div class="details">
  Year: <%= album.year %><br>
  Studio: <%= album.studio %><br>
  Live: <%= album.live %>
  <br>
  <%= link_to 'View Album', album_url(album) %>
  <br>
  <%= link_to 'Edit Album', edit_album_url(album) %>
  <%= link_to 'Delete Album',
  album_url(album),
  method: :delete,
  data: { confirm: "Delete#{album.title} from the database?"} %>
</div>
<br>

music_app/app/views/albums/_album_form.html.erb
<%
if action == :new
  action_url = albums_url
  edit_method = ""
  button_label = "Add this album to #{@band.name}"
else
  action_url = album_url(@album)
  edit_method = '<input type="hidden" name="_method" value="patch">'.html_safe
  button_label = "Edit #{@album.title}"
end
%>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <%= edit_method %>
  <label for="band_name">Band</label>
  <input id="band_name" type="text" value="<%= @band.name %>" disabled>
  <input type="hidden" name="album[band_id]" value="<%= @band.id %>">
  <br>
  <label for="album_title">Title</label>
  <input id="album_title" type="text" name="album[title]" value=" <%= @album.title %>">
  <br>
  <label for="album_year">Year</label>
  <input id="album_year" type="text" name="album[year]" value=" <%= @album.year %>">
  <br>
  <label for="studio">Studio</label>
  <select id="studio" name="album[studio]">
    <option value="true">True</option>
    <option value="false">False</option>
  </select>
  <br>
  <label for="live">Live</label>
  <select id="live" name="album[live]">
    <option value="true">True</option>
    <option value="false">False</option>
  </select>
  <br>
  <input type="submit" value=" <%= button_label %>">
</form>

music_app/app/views/albums/edit.html.erb
<% content_for :header do%>
  <h1><%= @band.name %></h1>
<% end %>

<%= render 'album_form', action: :edit %>

<br>
<%= link_to 'Back to band', band_url(@band) %>

music_app/app/views/albums/new.html.erb
<% content_for :header do%>
  <h1><%= @band.name %></h1>
<% end %>



<%= link_to 'Back to band', band_url(@band) %>

music_app/app/views/albums/show.html.erb
<% content_for :header do%>
  <h1><%= @album.title %></h1>
<% end %>

Band: <%= @band.name %><br>
Year: <%= @album.year %><br>
Studio: <%= @album.studio %><br>
Live: <%= @album.live %><br>
<%= link_to 'Edit Album', edit_album_url(@album) %>
<%= link_to 'Delete Album',
album_url(@album),
method: :delete,
data: { confirm: "Delete#{@album.title} from the database?"} %>

<br>
<br>
<%= link_to "Back to #{@band.name}", band_url(@band) %>

music_app/app/views/bands/_band.html.erb
<li>
  <%= link_to "#{band.name}", band_url(band) %>
</li>

music_app/app/views/bands/_band_form.html.erb
<%
if action == :new
  action_url = bands_url
  edit_method = ''
  button_name = 'Create new band'
else
  action_url = band_url(band)
  edit_method = '<input type="hidden" name="_method" value="patch">'.html_safe
  button_name = 'Edit this band'
end
%>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <%= edit_method %>
  <label for="band_name">Band Name</label>
  <input id="band_name" type="text" name="band[name]" value="<%= @band.name %>">
  <input type="submit" value=" <%= button_name %>">
</form>

music_app/app/views/bands/edit.html.erb
<% content_for :header do %>
  <h1>Edit: <%= @band.name %></h1>
<% end %>

<%= render 'band_form', action: :edit, band: @band %>

music_app/app/views/bands/index.html.erb
<% content_for :header do%>
  <h1>Bands</h1>
<% end %>

<ul>
  <%= render @bands %>
</ul>
<br>
<%= link_to "Add new band", new_band_url %>

music_app/app/views/bands/new.html.erb
<% content_for :header do %>
  <h1>Add a band</h1>
<% end %>

<%= render 'band_form', action: :new, band: @band %>

music_app/app/views/bands/show.html.erb
<% content_for :header do%>
  <h1><%= @band.name %></h1>
<% end %>

<%= render @band.albums %>

<div class="band-options">
  <%= button_to "Add an album", new_band_album_url(@band), method: :get %>
  <%= button_to "Edit Band", edit_band_url(@band), method: :get %>
  <%= button_to "Delete Band",
                band_url(@band),
                method: :delete,
                data: { confirm: "Delete #{@band.name} from the database?"}%>
</div>
<br>
<%= link_to 'Back to bands', bands_url %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeMusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <main>
      <header>
        <% if current_user %>
          <div class="welcome-message">
            <%= link_to 'BANDS', bands_url %>
            <%= "|" %>
            <%= "Welcome, " %>
            <%= link_to "#{current_user.email}", user_url(current_user) %>
          </div>
          <div class="header-buttons">
            <%= button_to 'Log Out', session_url, method: :delete %>
          </div>
        <% else %>
          <div class="welcome-message">
            <%= link_to 'HOME', bands_url %>
            <%= "|" %>
          </div>
          <div class="header-buttons">
            <%= button_to "Sign Up", new_user_url, method: :get %>
            <%= button_to "Sign In", new_session_url, method: :get %>
          </div>
        <% end %>
      </header>
      <div class="title">
        <h1>Awesome Music App</h1>
      </div>
      <div class="header-yield">
        <%= yield :header %>
      </div>
      <% flash[:errors] && flash[:errors].each do |error_msg| %>
        <%= error_msg %>
        <br>
      <% end %>
      <br>
      <%= yield %>
    </main>
  </body>
</html>

music_app/app/views/shared/_user_form.html.erb
<% if action == :sign_up
    action_url = users_url
  else
    action_url = session_url
  end %>

<form action=" <%= action_url %>" method="post">
  <%= auth_token %>
  <label for="user_email">Email</label>
  <input id="user_email" type="text" name="user[email]" value="">
  <br>
  <label for="user_password">Password</label>
  <input id="user_password" type="password" name="user[password]" value="">
  <br>
  <input type="submit" value=" <%= action %>">
</form>

music_app/app/views/users/new.html.erb
<% content_for :header do %>
  <h1>Sign Up</h1>
<% end %>

<p>Sign up for a new account</p>
<%= render 'shared/user_form', action: :sign_up %>

music_app/app/views/users/show.html.erb
<% content_for :header do %>
  <h1>User: <%= @user.email %></h1>
<% end %>

Joined: <%= @user.created_at %>